import os
import requests
from io import BytesIO
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor

from utils.logger import get_logger
from utils.config import Config

logger = get_logger(__name__)

def create_presentation_service(slides_data, font_name="Calibri", output_path="output.pptx"):
    """
    Create a PowerPoint presentation from slide data.
    Refactored from utils/ppt_utils.py into this service.
    """
    logger.info(f"Creating presentation at {output_path} with {len(slides_data)} slides.")
    
    prs = Presentation()

    # Helper to set font
    def set_font(run, size, bold=False):
        run.font.name = font_name
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.color.rgb = RGBColor(0, 0, 0) # Force Black

    # Title Slide
    if slides_data:
        # Use the first slide data for the title slide or generic
        # Ideally, the first item in slides_data acts as the title/intro if we want.
        # But per previous logic, we create a title slide separately based on the first slide's title?
        # Let's align with the old logic: Create Title Slide + Content Slides.
        
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        
        main_title = slides_data[0].get('title', 'Presentation')
        title.text = main_title
        subtitle.text = "Generated by Agentic AI"
        
        # Apply font to title slide
        for paragraph in title.text_frame.paragraphs:
            for run in paragraph.runs:
                set_font(run, 44, True)

    # Content Slides
    for slide_data in slides_data: 
        try:
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            shapes = slide.shapes

            # Title
            title_shape = shapes.title
            title_shape.text = slide_data['title']
            for paragraph in title_shape.text_frame.paragraphs:
                for run in paragraph.runs:
                    set_font(run, 36, True)

            # Content (Bullets) - USING MANUAL TEXT BOX TO ENSURE VISIBILITY
            # Layout: Text on Left (0.5 inch margin, 5 inch width), Image on Right.
            
            left = Inches(0.5)
            top = Inches(1.5)
            width = Inches(5.0)
            height = Inches(5.0)
            
            # Check if we have an image to decide layout
            image_url = slide_data.get('image_url')
            # If dummy image or None, treat as image present only if it's a real URL or we want to show dummy?
            # Old logic: if image_url exists
            
            if not image_url:
                width = Inches(9.0) # Full width if no image

            textbox = slide.shapes.add_textbox(left, top, width, height)
            tf = textbox.text_frame
            tf.word_wrap = True
            
            content_text = slide_data.get('content', '')
            
            if not content_text:
                 content_text = "No content generated for this slide."
            
            points = content_text.split('\n')
            points = [p for p in points if p.strip()]
            if not points:
                 points = ["No content available."]

            # First point
            tf.text = points[0]
            # Apply formatting to first paragraph
            for p in tf.paragraphs:
                p.font.size = Pt(22)
                p.font.name = font_name
                p.font.color.rgb = RGBColor(0, 0, 0) # Black

            # Subsequent points
            for point in points[1:]:
                p = tf.add_paragraph()
                p.text = point.strip()
                p.level = 0
                p.font.size = Pt(22)
                p.font.name = font_name
                p.font.color.rgb = RGBColor(0, 0, 0) # Black
                p.space_before = Pt(6) # Add some spacing

            # Image
            if image_url:
                try:
                    # Add User-Agent to avoid 403 Forbidden
                    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
                    response = requests.get(image_url, headers=headers, timeout=10)
                    
                    if response.status_code == 200:
                        image_stream = BytesIO(response.content)
                        # Position: Left=5.8 inches, Top=1.8 inches, Width=3.8 inches
                        shapes.add_picture(image_stream, Inches(5.8), Inches(1.8), width=Inches(3.8))
                        logger.debug(f"Added image to slide: {slide_data['title']}")
                    else:
                        logger.warning(f"Image download failed code {response.status_code} for {image_url}")
                except Exception as e:
                    logger.error(f"Failed to add image to slide: {e}")
        
        except Exception as e:
            logger.error(f"Error building slide '{slide_data.get('title', 'Unknown')}': {e}", exc_info=True)

    try:
        prs.save(output_path)
        logger.info(f"Presentation saved successfully to {output_path}")
        return output_path
    except Exception as e:
        logger.error(f"Failed to save PPTX file: {e}", exc_info=True)
        return ""
