"""
Builder Service
---------------
Creates PowerPoint presentations from structured slide data using python-pptx.
Handles layout, fonts, images, and formatting.
"""

import os
import requests
from io import BytesIO
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor

from utils.logger import get_logger
from config.settings import Config

logger = get_logger(__name__)


def create_presentation_service(
    slides_data: list,
    font_name: str = "Calibri",
    output_path: str = "output.pptx",
) -> str:
    """
    Create a PowerPoint presentation from structured slide data.

    Generates a title slide from the first slide's title, then creates
    content slides with text and optional images for all slides.

    Args:
        slides_data: List of slide dicts with keys:
            - ``title`` (str): Slide title
            - ``content`` (str): Bullet-point text (newline-separated)
            - ``image_url`` (str, optional): URL of the slide image
        font_name: Font to use throughout the presentation.
        output_path: Destination file path for the .pptx output.

    Returns:
        str: The file path of the saved .pptx, or empty string on failure.
    """
    logger.info(f"Creating presentation at {output_path} with {len(slides_data)} slides.")

    prs = Presentation()

    def set_font(run, size, bold=False):
        """Apply consistent font styling to a text run."""
        run.font.name = font_name
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.color.rgb = RGBColor(0, 0, 0)

    # ── Title Slide ──────────────────────────────────────────────────
    if slides_data:
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]

        main_title = slides_data[0].get("title", "Presentation")
        title.text = main_title
        subtitle.text = "Generated by Agentic AI"

        for paragraph in title.text_frame.paragraphs:
            for run in paragraph.runs:
                set_font(run, 44, True)

    # ── Content Slides ───────────────────────────────────────────────
    for slide_data in slides_data:
        try:
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            shapes = slide.shapes

            # Title
            title_shape = shapes.title
            title_shape.text = slide_data["title"]
            for paragraph in title_shape.text_frame.paragraphs:
                for run in paragraph.runs:
                    set_font(run, 36, True)

            # Content layout: text on left, image on right
            left = Inches(0.5)
            top = Inches(1.5)
            width = Inches(5.0)
            height = Inches(5.0)

            image_url = slide_data.get("image_url")
            if not image_url:
                width = Inches(9.0)  # Full width when no image

            textbox = slide.shapes.add_textbox(left, top, width, height)
            tf = textbox.text_frame
            tf.word_wrap = True

            content_text = slide_data.get("content", "")
            if not content_text:
                content_text = "No content generated for this slide."

            points = [p for p in content_text.split("\n") if p.strip()]
            if not points:
                points = ["No content available."]

            # First point
            tf.text = points[0]
            for p in tf.paragraphs:
                p.font.size = Pt(22)
                p.font.name = font_name
                p.font.color.rgb = RGBColor(0, 0, 0)

            # Subsequent points
            for point in points[1:]:
                p = tf.add_paragraph()
                p.text = point.strip()
                p.level = 0
                p.font.size = Pt(22)
                p.font.name = font_name
                p.font.color.rgb = RGBColor(0, 0, 0)
                p.space_before = Pt(6)

            # Image embedding
            if image_url:
                try:
                    headers = {
                        "User-Agent": (
                            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                            "AppleWebKit/537.36 (KHTML, like Gecko) "
                            "Chrome/91.0.4472.124 Safari/537.36"
                        )
                    }
                    response = requests.get(image_url, headers=headers, timeout=Config.IMAGE_FETCH_TIMEOUT)

                    if response.status_code == 200:
                        image_stream = BytesIO(response.content)
                        shapes.add_picture(image_stream, Inches(5.8), Inches(1.8), width=Inches(3.8))
                        logger.debug(f"Added image to slide: {slide_data['title']}")
                    else:
                        logger.warning(
                            f"Image download failed (HTTP {response.status_code}) for {image_url}"
                        )
                except requests.Timeout:
                    logger.error(f"Image download timeout for slide '{slide_data['title']}'")
                except Exception as e:
                    logger.error(f"Failed to add image to slide: {e}")

        except Exception as e:
            logger.error(
                f"Error building slide '{slide_data.get('title', 'Unknown')}': {e}",
                exc_info=True,
            )

    # ── Save Presentation ────────────────────────────────────────────
    try:
        prs.save(output_path)
        logger.info(f"Presentation saved successfully to {output_path}")
        return output_path
    except Exception as e:
        logger.error(f"Failed to save PPTX file: {e}", exc_info=True)
        return ""
