from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
import requests
from io import BytesIO

def create_presentation(slides_data, font_name="Arial", output_path="output.pptx"):
    prs = Presentation()

    # Helper to set font
    def set_font(run, size, bold=False):
        run.font.name = font_name
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.color.rgb = RGBColor(0, 0, 0) # Force Black

    # Title Slide
    if slides_data:
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        
        main_title = slides_data[0].get('title', 'Presentation')
        title.text = main_title
        subtitle.text = "Generated by Agentic AI"
        
        # Apply font to title slide
        for paragraph in title.text_frame.paragraphs:
            for run in paragraph.runs:
                set_font(run, 44, True)

    # Content Slides
    for slide_data in slides_data: # Skip/Handle title differently? Ideally outline has all slides.
        # Check if it's the first slide (Title), if so, we already added it. 
        # Actually, let's just make the planner output strictly content slides or handle title explicitely.
        # Ideally, Planner gives a list of slides including the title slide.
        # For simplicity, let's assume the first item IS the title slide content, but we used generic title above.
        # Let's just loop and create standard content slides for ALL items for now to be safe, or check index.
        
        bullet_slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes

        # Title
        title_shape = shapes.title
        title_shape.text = slide_data['title']
        for paragraph in title_shape.text_frame.paragraphs:
            for run in paragraph.runs:
                set_font(run, 36, True)

        # Content (Bullets) - USING MANUAL TEXT BOX TO ENSURE VISIBILITY
        # Layout: Text on Left (0.5 inch margin, 5 inch width), Image on Right.
        
        left = Inches(0.5)
        top = Inches(1.5)
        width = Inches(5.0)
        height = Inches(5.0)
        
        # Check if we have an image to decide layout
        image_url = slide_data.get('image_url')
        if not image_url:
            width = Inches(9.0) # Full width if no image

        textbox = slide.shapes.add_textbox(left, top, width, height)
        tf = textbox.text_frame
        tf.word_wrap = True
        
        content_text = slide_data.get('content', '')
        print(f"DEBUG: Slide '{slide_data.get('title')}' content length: {len(content_text)}")
        
        if not content_text:
             content_text = "No content generated for this slide."
        
        points = content_text.split('\n')
        points = [p for p in points if p.strip()]
        if not points:
             points = ["No content available."]

        # First point
        tf.text = points[0]
        # Apply formatting to first paragraph
        for p in tf.paragraphs:
            p.font.size = Pt(22)
            p.font.name = font_name
            p.font.color.rgb = RGBColor(0, 0, 0) # Black

        # Subsequent points
        for point in points[1:]:
            p = tf.add_paragraph()
            p.text = point.strip()
            p.level = 0
            p.font.size = Pt(22)
            p.font.name = font_name
            p.font.color.rgb = RGBColor(0, 0, 0) # Black
            p.space_before = Pt(6) # Add some spacing

        # Image
        if image_url:
            print(f"DEBUG: Attempting to download image: {image_url}")
            try:
                # Add User-Agent to avoid 403 Forbidden from some servers
                headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
                response = requests.get(image_url, headers=headers, timeout=10)
                
                if response.status_code == 200:
                    image_stream = BytesIO(response.content)
                    
                    # Add image on the right side
                    # Text ends at 0.5 + 5.0 = 5.5.
                    # Start image at 5.7 to give gap.
                    # Width available: 10 - 5.7 - 0.5 (margin) = 3.8 ~ 4.0
                    try:
                        # Position: Left=5.8 inches, Top=2.0 inches (approx align with text start), Width=3.8 inches
                        # Note: body_shape.top is usually around 1.5 or 2 depending on master. We can look it up or guess.
                        # Safe guess: align with common body top ~ 1.5-2.0
                        shapes.add_picture(image_stream, Inches(5.8), Inches(1.8), width=Inches(3.8))
                        print(f"DEBUG: Successfully added image to slide {slide_data['title']}")
                    except Exception as e:
                        print(f"DEBUG: Failed to add image to PPT shape: {e}")
                else:
                     print(f"DEBUG: Image download failed with status code: {response.status_code}")
            except Exception as e:
                print(f"DEBUG: Failed to download image: {e}")

    prs.save(output_path)
    return output_path
